CREATE DATABASE nithin;
use nithin;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


